// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvcambtabzeiuezdydim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2Y2FtYnRhYnplaXVlemR5ZGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDkwNTksImV4cCI6MjA3MDM4NTA1OX0.5zIqTwr2LAzIWgKXeZ6XCAU4xrzHTDhzoFRqqjtL4OU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});